applications/busqueda/urls.py
from django.urls import path

app_name = "busqueda_app"
from . import views

urlpatterns = [
    path('lista-busquedas/',
    views.BusquedaListView.as_view(),
    name ='busquedas'
    ),
    path('nuevo-partido/',
    views.BusquedaCreateView.as_view(),
    name ='NuevoPartido'
    ),

]

applications/jugador/urls.py
from django.urls import path


from . import views

app_name = "jugador_app"

urlpatterns = [
    
    #pagina de inicio
    path("",
     views.HomeView.as_view(),
     name='home',
     ),
     path("pagina-principal/",
     views.MainPageView.as_view(),
     name='pagina_principal',
     ),
     path("Felicidades/",
     views.RegistroCorrecto.as_view(),
     name='registroCorrecto',
     ),

     path('registrar-jugador/',
     views.JugadorCreateView.as_view(),
     name='registrar_jugador',
    ),
    path('jugadores-disponibles/',
    views.JugadorListView.as_view(),
    name='jugadores_disponibles',
    ),
    path('detalle-jugador/<pk>/',
    views.JugadorDetailView.as_view(),
    name='jugador_detalle',
    ),
  path('signup/',
     views.SignUpView.as_view(),
     name='signup',
    ),
    

]

proyecto_final/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('applications.jugador.urls')),

    path("", include('applications.categoria.urls')),
    path("", include('applications.busqueda.urls')),
  
    #para manejo de registro de usuarios
    #esta url esta en el codigo fuente de django automaticamente con muchas urls para manejo de usuarios
    path("accounts/",include('django.contrib.auth.urls')),

# concateno a este paquete de arrays otro para los multimedia
]  + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#Que genere en base a este archivo media a esta configuración media URL que nos genere una web
# para la ruta de un documento que esté guardado en nuestro proyecto paralelo.

templates/includes/carousel.html
       {% load static %}

       <div id="myCarousel" class="carousel slide" data-ride="carousel">

            <!--Indicadores-->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide="0" class="item1 active" ></li>
            <li data-target="#myCarousel" data-slide="1" class="item2" ></li>
            <li data-target="#myCarousel" data-slide="2" class="item3 " ></li>
          </ol>
            <!--Wrapper for slides-->
          <div class="carousel-inner">
              <div class="carousel-item active" >
                  <img src= "{% static 'img/carrousel2.jpg' %}"  class="d-block w-100" alt="">
                  <div class="carousel-caption">
             
                  <h2>El futbol no se abandona</h2>
                  <h5>No dejes de jugar.</h5>
                  </div>
              </div>
  
              <div class="carousel-item " >
                  <img src= "{% static 'img/carrousel5.jpg' %}"  class="d-block w-100" alt="">
                  <div class="carousel-caption">
                  <h1>Encontra tu equipo ideal</h1>
                  <h5>No dejes de jugar.</h5>
              </div>
              </div>
  
              <div class="carousel-item " >
                <img src= "{% static 'img/carrousel1.jpg' %}"  class="d-block w-100" alt="">
                <div class="carousel-caption">
                <h1>Que no te falten jugadores</h1>
                <h5>No dejes de jugar.</h5>
              </div>
              </div>
              <div class="carousel-item " >
                <img src= "{% static 'img/carrousel7.jpg' %}"  class="d-block w-100" alt="">
                <div class="carousel-caption">
                <h1>Que no te falten jugadores</h1>
                <h5>No dejes de jugar.</h5>
              </div>
              </div>
              <div class="carousel-item " >
                <img src= "{% static 'img/carousel6.jpg' %}"  class="d-block w-100" alt="">
                <div class="carousel-caption">
                <h1>Que no te falten jugadores</h1>
                <h5>No dejes de jugar.</h5>
              </div>
              </div>
             
          </div>
            <!--Controles-->
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Anterior</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Siguiente</span>
            </a>
          </div>
  
  <!--Codigo javascript-->
<script>

    $(document).ready(function(){
// Enable Carousel Indicators
$(".item1").click(function(){
  $("#myCarousel").carousel(0);
});
$(".item2").click(function(){
  $("#myCarousel").carousel(1);
});
$(".item3").click(function(){
  $("#myCarousel").carousel(2);
});
$(".item4").click(function(){
  $("#myCarousel").carousel(3);
});
  
// Enable Carousel Controls
$(".left").click(function(){
  $("#myCarousel").carousel("prev");
});
$(".right").click(function(){
  $("#myCarousel").carousel("next");
});
});

</script>

templates/includes/footer.html
  
  <!--INICIO PIE DE PÁGINA-->
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Quien suma?</strong> por <a href="https://www.linkedin.com/in/chiara-di-giannantonio-558bb0188/">Chiara Di Giannantonio</a>.  Twitter <a href="https://twitter.com/ChiaraDiGianna1" class="text-white">@ChiaraDiGianna</a>.</p>
      </p>
    </div>
  </footer>
<!-- FIN DE PIE DE PAGINA -->

templates/includes/header.html
{% load static %}
<header class=" bg-dark mb-auto d-flex w-100 h-50 p-3 mx-auto flex-column text-center text-white  shadow-5-strong">
    <nav class="nav nav-masthead justify-content-center float-md-end">
      <!--INICIO DEL LOGO CON ICONO -->
      
        <img src= "{% static 'img/logo2.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" >
        
          <h3 style="font-family:  Helvetica;">Te damos la bienvenida <strong>{{user.get_username}}</strong> </h3>  
        
      <!--FIN  DEL LOGO CON ICONO -->

      <!--INICIO DEL DROPDOWN -->
      <div class="dropdown show" style="margin: auto auto auto 10px;">
        <li class="nav-item dropdown">
          <a class="btn btn-secondary dropdown-toggle " href="#" role="button" id="dropdownBusquedaLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Opciones
          </a> 
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li>  <a class="dropdown-item" name="nuevoPartidoRedirect"  onClick="redirect()">Crear un partido</a>
              <script type="text/javascript">
                function redirect()
                {
                  window.location.href="{% url 'busqueda_app:NuevoPartido' %}";
                }
              </script></li>
            <li>  <a class="dropdown-item" name="nuevoJugadorRedirect"  onClick="redirect()">Registrar un jugador</a>
              <script type="text/javascript">
                function redirect()
                {
                  window.location.href="{% url 'jugador_app:registrar_jugador' %}";
                }
              </script></li>  
            <li> <a class="dropdown-item" href="#acercaDeNosotros">Acerca de nosotros</a></li>
            {% if user.is_authenticated  %}
            <!-- permito al usuario cerrar sesion -->
            <!-- añado el parametro next para añadir un url next
            que contiene la dirección url de esta pagina para redireccionar  -->
            <li> <a class="dropdown-item"  href="{% url 'logout' %}">Cerrar sesión</a></li>
            {% else %}
            <p>Inicia sesión para acceder</p>
            <a href="{% url 'login' %}?next={{request.path}}">Iniciar sesión</a>
            {% endif %}
          </ul>
        </li>
      </div>



    
       <!--FIN DEL DROPDOWN DE OPCIONES-->

        <!--INICIO BOTONES-->
      <li class="nav-item col-xs-6 ">
        
        <!-- <button class="btn btn-dark  my-2 my-sm-0 " type="submit">Jugadores</button> -->
        <a class="btn  rounded mx-1 btn-secondary" href="{% url 'jugador_app:jugadores_disponibles' %}">Jugadores</a>

      </li> 
      
      <li class="nav-item">
        <a class="btn mx-1 btn-secondary" href="{% url 'busqueda_app:busquedas' %}">Partidos</a>
      </li>
      <li class="nav-item">
        <a class="btn mx-1 btn-secondary" href="{% url 'jugador_app:pagina_principal' %}">Inicio</a>

      </li>
       <!--FIN BOTONES-->
    </nav>
</header>