applications/jugador/urls.py
from django.urls import path


from . import views

app_name = "jugador_app"

urlpatterns = [
    
    #pagina de inicio
    path("",
     views.HomeView.as_view(),
     name='home',
     ),
     path("pagina-principal/",
     views.MainPageView.as_view(),
     name='pagina_principal',
     ),
     path("Felicidades/",
     views.RegistroCorrecto.as_view(),
     name='registroCorrecto',
     ),

     path('registrar-jugador/',
     views.JugadorCreateView.as_view(),
     name='registrar_jugador',
    ),
    path('jugadores-disponibles/',
    views.JugadorListView.as_view(),
    name='jugadores_disponibles',
    ),
    path('detalle-jugador/<pk>/',
    views.JugadorDetailView.as_view(),
    name='jugador_detalle',
    ),
  path('signup/',
     views.SignUpView.as_view(),
     name='signup',
    ),
    

]

proyecto_final/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('applications.jugador.urls')),

    path("", include('applications.categoria.urls')),
    path("", include('applications.busqueda.urls')),
  
    #para manejo de registro de usuarios
    #esta url esta en el codigo fuente de django automaticamente con muchas urls para manejo de usuarios
    path("accounts/",include('django.contrib.auth.urls')),

# concateno a este paquete de arrays otro para los multimedia
]  + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#Que genere en base a este archivo media a esta configuración media URL que nos genere una web
# para la ruta de un documento que esté guardado en nuestro proyecto paralelo.

templates/home.html
{% extends "base/base.html" %}

{% load static %}


{% block titulo %} 

    home

{% endblock titulo %}

{% block body %}


<!--navbar Inicio-->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    <img src= "{% static 'img/logo2.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    Quien suma?
  </a>
  <form class="form-inline">
   <a type="button" class="btn btn btn-dark my-2 my-sm-0 " href="{% url 'login' %}">Iniciar sesion</a>
   <a type="button" class="btn btn btn-dark my-2 my-sm-0 " href="{% url 'jugador_app:signup' %}">Crear cuenta</a>
  </form>
</nav>

<!--Fin de navbar -->



{% block head %} 

<style>
*, ::after, ::before {
    box-sizing: border-box;
}

body {
  text-align: center;
  background-color: #212529;

}

.cover-container {
  max-width: 40em;
}


.fondocard{

    background-color: #cbd1f2;
}
.fondonavegacion{

    background-color: #cbd1f2;
}

.carta-block , .img-container{
    position: relative;
    margin: 0 auto 20px auto;
    max-width: 819px;
    box-sizing: border-box;
}

.fade.in{
    opacity: 1;
}
section.content.light a:not(.btn) {
    color: black;
}
a:active, a:hover {
    outline: 0;
}

.bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }



</style>
{% endblock head %} 

<!--Fin de navbar -->

<!--Carousel-->

{% include 'includes/carousel.html' %}


<!--Fin de Carousel-->

<div id="acercaDeNosotros" class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column  text-white bg-dark">

  
    <br><br>


<!-- inicio de About us-->

    <div class="cover-container d-flexp-3 mx-auto flex-column">
    
      <main class="px-3">
        <h1>CONECTAMOS JUGADORES CON EQUIPOS.</h1><br>
        <p class="lead">Estas cansado de quedarte en casa sin jugar? Ahora podes organizar tus partidos, invitar o sumarte a partidos. Si ningun equipo te interesa... <strong>¡organizate uno!</strong></p>
        <br><h4><strong>Contactanos</strong></h4>
        <p class="lead">
          info@quiensuma.com
        </p>


      </main>
    
      
    </div>

<!-- Fin de About us-->

<!--INICIO PIE DE PÁGINA-->

{% include 'includes/footer.html' %}


<!-- FIN DE PIE DE PAGINA -->

</div>





{% endblock body %}

templates/pagina_principal.html
{% extends "base/base.html" %}

{% load static %}


{% block head %} 

<style>
*, ::after, ::before {
    box-sizing: border-box;
}

body {
  text-align: center;
  background-color: #212529;

}

.cover-container {
  max-width: 40em;
}


.fondocard{

    background-color: #cbd1f2;
}
.fondonavegacion{

    background-color: #cbd1f2;
}

.carta-block , .img-container{
    position: relative;
    margin: 0 auto 20px auto;
    max-width: 819px;
    box-sizing: border-box;
}

.fade.in{
    opacity: 1;
}
section.content.light a:not(.btn) {
    color: black;
}
a:active, a:hover {
    outline: 0;
}

.bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }



</style>
{% endblock head %} 

{% block body %}

{% include 'includes/header.html' %}




<!--Fin de navbar -->

<!--Carousel-->

{% include 'includes/carousel.html' %}


<!--Fin de Carousel-->

<div id="acercaDeNosotros" class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column  text-white bg-dark">

  
    <br><br>


<!-- inicio de About us-->

    <div class="cover-container d-flexp-3 mx-auto flex-column">
    
      <main class="px-3">

        <h1>CONECTAMOS JUGADORES CON EQUIPOS.</h1><br>
        <p class="lead">Estas cansado de quedarte en casa sin jugar? Ahora podes organizar tus partidos, invitar o sumarte a partidos. Si ningun equipo te interesa... <strong>¡organizate uno!</strong></p>
        <br><h4><strong>Contactanos</strong></h4>
        <p class="lead">
          info@quiensuma.com
        </p>


      </main>
    
      
    </div>

<!-- Fin de About us-->

<!--INICIO PIE DE PÁGINA-->

{% include 'includes/footer.html' %}


<!-- FIN DE PIE DE PAGINA -->

</div>





{% endblock body %}