applications/jugador/urls.py
from django.urls import path


from . import views

app_name = "jugador_app"

urlpatterns = [
    
    #pagina de inicio
    path("",
     views.HomeView.as_view(),
     name='home',
     ),
     path("pagina-principal/",
     views.MainPageView.as_view(),
     name='pagina_principal',
     ),
     path("Felicidades/",
     views.RegistroCorrecto.as_view(),
     name='registroCorrecto',
     ),

     path('registrar-jugador/',
     views.JugadorCreateView.as_view(),
     name='registrar_jugador',
    ),
    path('jugadores-disponibles/',
    views.JugadorListView.as_view(),
    name='jugadores_disponibles',
    ),
    path('detalle-jugador/<pk>/',
    views.JugadorDetailView.as_view(),
    name='jugador_detalle',
    ),
  path('signup/',
     views.SignUpView.as_view(),
     name='signup',
    ),
    

]

proyecto_final/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('applications.jugador.urls')),

    path("", include('applications.categoria.urls')),
    path("", include('applications.busqueda.urls')),
  
    #para manejo de registro de usuarios
    #esta url esta en el codigo fuente de django automaticamente con muchas urls para manejo de usuarios
    path("accounts/",include('django.contrib.auth.urls')),

# concateno a este paquete de arrays otro para los multimedia
]  + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#Que genere en base a este archivo media a esta configuración media URL que nos genere una web
# para la ruta de un documento que esté guardado en nuestro proyecto paralelo.

applications/jugador/models.py
from django.db import models
from ckeditor.fields import RichTextField

from applications.categoria.models import Categoria, Subcategoria
from datetime import date

from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin
# from django.contrib.auth.models import User
# from django.db.models.signals import post_save
# from django.dispatch import receiver

class Jugador(models.Model):
    SEXO_CHOICES = (
    ('0', 'Femenino'),
    ('1','Masculino'),
    )
    PIEHABIL_CHOICES = (
    ('0', 'Derecho'),
    ('1','Izquierdo'),
    ('2','Indistinto')
    )
    PROVINCIAS_CHOICES = (
    ('0', 'Buenos Aires'),
    ('1','Cordoba'),
    ('2','Rosario'),
    )
   
    """Modelo para tabla Jugador"""
    
    nombre = models.CharField("nombres", max_length=30,)
    apellido = models.CharField("apellidos", max_length=60)
    fecha_nacimiento = models.DateField("fecha de nacimiento", auto_now=False, auto_now_add=False)
    categoria = models.ManyToManyField(Subcategoria)
    sexo =  models.CharField("sexo",max_length=50,choices=SEXO_CHOICES)
    correo = models.EmailField(max_length=254, unique=True) #email unico 
    descripcion = RichTextField(blank=True,)
    #info de direccion
    provincia =  models.CharField("provincia",max_length=50,choices=PROVINCIAS_CHOICES,default="Buenos Aires")
    localidad = models.CharField("localidad", max_length=100,default="vacio")
    imagen = models.ImageField(upload_to='jugador', blank=True,)
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'Jugador'
        verbose_name_plural = 'Jugadores'
        ordering = ['nombre'] #ordena por nombre
        unique_together = ('nombre','apellido')#no permite que la combinacion de estos se repita en la BD


    def calcular_años(self):
        today = date.today()
        return today.year - self.fecha_nacimiento.year - ((today.month, today.day) < (self.fecha_nacimiento.month, self.fecha_nacimiento.day))

    def __str__(self):
        return str(self.id) +  '-' +   self.nombre +  '-' + self.apellido 

# @receiver(post_save, sender=User)
# def update_user_jugador(sender, instance, created, **kwargs):
#     if created:
#         Jugador.objects.create(user=instance)
#     instance.profile.save()

applications/jugador/forms.py
from django import forms

from .models import Jugador

class SingUpForm(forms.ModelForm):

    class Meta:
        model = Jugador
        fields =  ('__all__')
        widgets = {

            'categoria' : forms.CheckboxSelectMultiple()
        }
# class SingUpForm(UserCreationForm):
#     correo = forms.EmailField()
#     sexo = forms.CharField()
#     localidad = forms.CharField()
#     provincia = forms.CharField()
#     imagen=forms.ImageField()
#     nombre=forms.CharField()
#     apellido=forms.CharField()
#     fecha_nacimiento = forms.DateField(help_text='Formato: YYYY-MM-DD')
#     descripcion = RichTextField()
   
#     class Meta:
#         model = User
#         fields =  ("username", "password1", "password2",'correo','sexo','localidad','apellido','nombre','provincia','imagen','fecha_nacimiento','categoria','descripcion')
#         widgets = {

#             'categoria' : forms.CheckboxSelectMultiple()
#         }

#     def save(self,commit=True):
#         jugador = super(SingUpForm,self).save(commit=False)
#         jugador.correo = self.cleaned_data['correo']
#         jugador.sexo =self.cleaned_data['sexo']
#         jugador.localidad = self.cleaned_data['localidad']
#         jugador.apellido = self.cleaned_data['apellido']
#         jugador.nombre = self.cleaned_data['nombre']
#         jugador.provincia = self.cleaned_data['provincia']
#         jugador.imagen = self.cleaned_data['foto de perfil'] 
#         jugador.fecha_nacimiento = self.cleaned_data['fecha de nacimiento']
#         jugador.descripcion=self.cleaned_data['Describa brevemente su esilo de juego']
#         if commit:
#             jugador.save()
#         return jugador

applications/jugador/views.py
# Create your views here.
from django.views.generic import DetailView,CreateView,ListView,TemplateView
from .models import Jugador
from .forms import SingUpForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm



class SignUpView(CreateView):
     """Vista que usa el formulario de Django para 
         registrar un usuario"""
     model = Jugador
     template_name = "registration/signup.html"
     success_url= reverse_lazy('jugador_app:registroCorrecto')
     form_class= UserCreationForm
     
# class SignUpView(CreateView):
#      """Vista que usa el formulario de Django para 
#          registrar un jugeaodr/usuario"""
#      model = Jugador
#      template_name = "registration/signup.html"
#      success_url= reverse_lazy('jugador_app:registroCorrecto')
#      form_class= SingUpForm 

class JugadorCreateView(LoginRequiredMixin,CreateView):
    """Vista para registrar un jugeaodr"""
    """mixin para que solo me deje acceder si estoy authorizada"""
    model = Jugador
    template_name = "jugador/registrar_jugador.html"
    success_url= reverse_lazy('jugador_app:registroCorrecto')
    form_class= SingUpForm
    
class RegistroCorrecto(TemplateView):
    template_name = "jugador/registro_correcto.html"



class HomeView(TemplateView):
    """Vista que carga la pagina de inicio sin logueo"""
    template_name = "home.html"

class MainPageView(LoginRequiredMixin,TemplateView):
    """Vista que carga la pagina principal cuando alguien ya esta logueado"""
    template_name = "pagina_principal.html"



class JugadorListView(LoginRequiredMixin,ListView):
    # model = Jugador --> no hace falta porque sobre escribo uso query set
    template_name = "jugador/jugadores_disponibles.html"
    ordering = 'nombre'
    context_object_name = 'listaJugadores'
    paginate_by = 6


    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword",'')

        filtrarTodo = Jugador.objects.filter(
            nombre__icontains= palabra_clave,
            #icontains busca palabra clave dentro de nombre 
            #si esta vacio no filtra
            #categoria__icontans = palabra_clave

        )
        return filtrarTodo

class JugadorDetailView(LoginRequiredMixin,DetailView):
    model = Jugador
    template_name = "jugador/detalle_jugador.html"
     
    def get_context_data(self, **kwargs):
        context = super(JugadorDetailView, self).get_context_data(**kwargs)
        return context
    

templates/jugador/detalle_jugador.html
{% extends "base/base.html" %}
{% load static %}

{% block titulo %} 

  detalle jugador

{% endblock titulo %}


{% block body %}
{% include 'includes/header.html' %}

<div class="container">
    <div class="main-body">
    
          <!-- Breadcrumb -->
          <!-- <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">Home</a></li>
              <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
              <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
          </nav> -->
          <!-- /Breadcrumb -->
    <br>
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    {% if jugador.imagen %}
                   
                        <img src= " {{jugador.imagen.url}} " alt="Admin" class="rounded-circle" width="150">
                    {% else %}

                              <!--Si no tiene una foto propia le pongo la de un avatar segun su sexo-->
                        {% if jugador.get_sexo_display == 'Femenino'  %}
                            <img src= "{% static 'img/WomanAvatar.png' %}"  alt="Admin" class="rounded-circle" width="150">
                            {% else %}
                            <img src= "{% static 'img/MasculinoAvatar.jpg' %}"  alt="Admin" class="rounded-circle" width="150">
                            {% endif %}
                    {% endif %}


                    <div class="mt-3">
                      <h4>{{jugador.nombre}} {{jugador.apellido}}</h4>
                      <button class="btn btn-primary">Conectar</button>
                      <button class="btn btn-outline-primary">Chat</button>
                    </div>
                  </div>
                </div>
              </div>
<!-- 
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0">Pie habil</h6>
                    <span class="text-secondary">{{jugador.get_pie_habil_display}}</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d=  "{% static 'img/pieIcon.png' %}" ></path></svg>Github</h6>
                    <span class="text-secondary">bootdey</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
                    <span class="text-secondary">@bootdey</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                    <span class="text-secondary">bootdey</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
                    <span class="text-secondary">bootdey</span>
                  </li>
                </ul>
              </div>

               -->
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Nombre completo</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                    {{jugador.nombre}} {{jugador.apellido}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Edad</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{jugador.calcular_años}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Sexo</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{jugador.get_sexo_display}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Posiciones</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">

                        {% for subcategoria in jugador.categoria.all %}
                        {{subcategoria.nombre_subcategoria}}
                        <br/>
                        {% endfor %}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Ubicacion de preferencia</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{jugador.get_provincia_display}}, {{jugador.localidad}}
                    </div>
                  </div>
                  <hr>
                
                  <hr>
              </div>
              
              <div >
                <div class="alert alert-success" role="alert">
                  <h4 class="alert-heading">Descripcion</h4>
                  {{jugador.descripcion|safe}}
                </div>
               </div>
              <!-- <div class="row gutters-sm">
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                      <small>Web Design</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Website Markup</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>One Page</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Mobile Template</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Backend API</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                      <small>Web Design</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Website Markup</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>One Page</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Mobile Template</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Backend API</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>



            </div>
          </div>

        </div>
    </div> -->



{% endblock body %}

templates/jugador/jugadores_disponibles.html
{% extends "base/base.html" %}



{% block titulo %} 

   jugadores disponibles

{% endblock titulo %}

{% block head %} 
<style>
  pagination > li > a,
.pagination > li > span {
    color: #676b90; 
}

.pagination > .active > a,
.pagination > .active > a:focus,
.pagination > .active > a:hover,
.pagination > .active > span,
.pagination > .active > span:focus,
.pagination > .active > span:hover {
    background-color: #5f6bd2;
    border-color:#1f2342;
}
.page-item.active .page-link {
    z-index: 1;
    color: #fff;
    background-color: #5f6bd2; 
    border-color: #5f6bd2;
}

  body{
background:var(--bs-body-color);
}
  h1{
    color:aliceblue;
  }
  table {
  margin: 15px;
  padding: 15px;
}

</style>
{% endblock head %}

{% block body %}
{% include 'includes/header.html' %}



<div class="container  text-center  px-4 ">
    <h1>Jugadores disponibles</h1>

<!--formulario para poder filtrar-->
    <form class="row gx-5" method="GET">{% csrf_token %}
      <div class="col">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Buscar jugador" name="kword" id="kword" aria-label="jugador a buscar" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="submit">Buscar</button>
            </div>
          </div>
      </div>
    </form>
  </div>


  <!--Tabla de jugadores-->
  <table class="table table-dark col-lg-6 col-md-8 mx-auto ">
    <thead>
      <tr>
        <th scope="col">NOMBRE</th>
        <th scope="col">POSICION</th>
        <th scope="col">SEXO</th>
        <th scope="col">EDAD</th>
        <th scope="col">LOCALIDAD/BARRIO</th>
        <th scope="col">ACCION</th>
      </tr>
    </thead>
    <tbody> 
    {% for j in listaJugadores %}
      <tr>
        <td>{{j.nombre}} {{j.apellido}}</td>
        <td>

          {% for subcategoria in j.categoria.all %}
              {{subcategoria.nombre_subcategoria}}
              <br/>
          {% endfor %}
        </td>
        <td>{{ j.get_sexo_display }}</td>
        <td>{{j.calcular_años}}</td>
        <td>{{j.localidad}}</td>
        <td><a class="btn btn-light" href="{% url 'jugador_app:jugador_detalle' j.id  %}">Ver</a>
        <!-- <td><button class="btn btn-outline-secondary" href="{% url 'jugador_app:jugador_detalle' j.id  %}" type="submit">Ver</button> -->
        </td>
      </tr>
    {% endfor %}

    </tbody>
  </table>
  <!--Fin de Tabla de jugadores-->



<!-- Paginacion -->
<div class="pagination justify-content-center" >
  <!--Si esta paginado-->
  {% if is_paginated %}
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          
          <!--page_obj hace referencia al obj que crea la paginacion
          Si hay una pagina previa, mostrame el simbolo para ir para atras
          sino mostramelo disabled-->
               
            <!--page_range tiene el num de paginas-->
          {% for pagina in paginator.page_range  %}

            {% if pagina == page_obj.number  %} 
            <li class="page-item active"><a class="page-link" href="?page={{pagina}}">{{pagina}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{pagina}}">{{pagina}}</a></li>
            {% endif %}
          {% endfor %}
        </ul>
      </nav>
    </div>

  {% endif %}
    
</div>
 <!-- Fin de Paginacion -->


{% endblock body %}

templates/jugador/registrar_jugador.html
{% extends "base/base.html" %}

{% block titulo %}Signup{% endblock titulo %}

{% block body %}
<br><br>
<div class="container">
    {% load crispy_forms_tags %}

    <form method="POST" enctype="multipart/form-data"     >{% csrf_token %}

        <div class="form-group">
            <div class="row">
                <div class="col-6">
                    {{form.nombre|as_crispy_field}}
                </div>
                <div class="col-6">
                    {{form.apellido|as_crispy_field}}     
                </div>
            </div>

        </div>
        <div class="form-group">
            {{form.correo|as_crispy_field}}
        </div>
        <div class="form-group">
            {{form.categoria|as_crispy_field}}
        </div>
        <div class="row">
            <div class="col-6">
                {{form.sexo|as_crispy_field}}
            </div>
            <div class="col-6">
                {{form.fecha_nacimiento|as_crispy_field}}     
            </div>
        </div>
        
        <div class="row">
            <div class="col-6">
                {{form.provincia|as_crispy_field}}
            </div>
            <div class="col-6">
                {{form.localidad|as_crispy_field}}     
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                {{form.descripcion|as_crispy_field}}
            </div>
        </div>
        <div class="form-group">
            {{form.imagen|as_crispy_field}}
        </div>

        <button type="submit" class="btn btn-success">Confirmar</button> 
      </form>
</div>
{% endblock body %}

templates/jugador/registro_correcto.html
{% extends "base/base.html" %}

{% block titulo %} 

Felicidades!

{% endblock titulo %}



{% block head %} 

<style>


</style>
{% endblock head %}

{% block body %}

<!--Solo si esta logueado lo dejo ver el header-->
{% if user.is_authenticated  %}
  {% include 'includes/header.html' %}
{% endif %}
<main >

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Felicidades !</h1>
        <p class="lead text-muted">Su registro se almaceno correctamente! Gracias por confiar en nosotros</p>
        <p>
   

          <a href="{% url 'jugador_app:home' %}" class="btn btn-secondary my-2">Volver al inicio</a>
        </p>
      </div>
    </div>
  </section>

</main>


{% endblock body %}